export { default as Benefits } from './Benefits';
export { default as Criteria } from './Criteria';
export { default as CTA } from './CTA';
export { default as Footer } from './Footer';
export { default as Gallery } from './Gallery';
export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as Process } from './Process';
export { default as SubmitApplication } from './SubmitApplication';
